# Generated by Django 3.2.16 on 2023-01-18 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binance_model',
            fields=[
                ('clientOrderId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('symbol', models.CharField(default='0', max_length=200)),
                ('orderId', models.CharField(default='0', max_length=200)),
                ('OrderListId', models.CharField(default='0', max_length=200)),
                ('executedQty', models.CharField(default='0', max_length=200)),
                ('price', models.CharField(default='0', max_length=200)),
                ('side', models.CharField(default='0', max_length=200)),
                ('status', models.CharField(default='0', max_length=200)),
                ('timeInForce', models.CharField(default='0', max_length=200)),
                ('transactTime', models.CharField(default='0', max_length=200)),
                ('type', models.CharField(default='0', max_length=200)),
                ('workingTime', models.CharField(default='0', max_length=200)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Binance_model',
            },
        ),
        migrations.CreateModel(
            name='Kucoin_model',
            fields=[
                ('symbol', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('orderId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('timeInforce', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('clientOid', models.CharField(max_length=200)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Kucoin_model',
            },
        ),
        migrations.CreateModel(
            name='Gate_model',
            fields=[
                ('symbol', models.CharField(max_length=200)),
                ('currency_pair', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('time_in_force', models.CharField(max_length=200)),
                ('orderId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Gate_model',
            },
        ),
        migrations.CreateModel(
            name='Fills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.CharField(max_length=200)),
                ('commissionAsset', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=200)),
                ('tradeId', models.CharField(max_length=200)),
                ('clientOrderId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_exchanges.binance_model')),
            ],
            options={
                'db_table': 'Fills',
            },
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('message', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('sr', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=200)),
                ('Exchange_name', models.CharField(max_length=200)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Exception',
            },
        ),
        migrations.CreateModel(
            name='Bitmex_model',
            fields=[
                ('orderID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=200)),
                ('clOrdId', models.CharField(max_length=200)),
                ('cumQty', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('ordStatus', models.CharField(max_length=200)),
                ('ordType', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('settleCurrency', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('timeInForce', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('transactTime', models.CharField(max_length=200)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bitmex_model',
            },
        ),
    ]
