# Generated by Django 4.1.4 on 2023-02-01 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_exchanges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binance_model",
            name="id",
            field=models.ForeignKey(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bitmex_model",
            name="id",
            field=models.ForeignKey(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exception",
            name="id",
            field=models.ForeignKey(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fills",
            name="clientOrderId",
            field=models.ForeignKey(
                db_column="clientOrderId",
                on_delete=django.db.models.deletion.CASCADE,
                to="user_exchanges.binance_model",
            ),
        ),
        migrations.AlterField(
            model_name="gate_model",
            name="id",
            field=models.ForeignKey(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="kucoin_model",
            name="id",
            field=models.ForeignKey(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
