# Generated by Django 3.2.16 on 2023-01-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fills',
            name='clientOrderId',
            field=models.ForeignKey(db_column='clientOrderId', on_delete=django.db.models.deletion.DO_NOTHING, to='user_exchanges.binance_model'),
        ),
    ]
