# Generated by Django 4.1.4 on 2023-02-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "user_exchanges",
            "0002_alter_binance_model_id_alter_bitmex_model_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exchanges",
            name="socket",
            field=models.CharField(default="dsgdfgsd", max_length=300),
        ),
        migrations.AddField(
            model_name="exchanges",
            name="status",
            field=models.CharField(default="1", max_length=200),
        ),
        migrations.CreateModel(
            name="KucoinKeys",
            fields=[
                ("api_key", models.CharField(max_length=500)),
                (
                    "secrets_key",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("passphrase", models.CharField(max_length=200)),
                (
                    "id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Kucoin_keys",
            },
        ),
        migrations.CreateModel(
            name="GateIoKeys",
            fields=[
                ("api_key", models.CharField(max_length=500)),
                (
                    "secrets_key",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Gate_keys",
            },
        ),
        migrations.CreateModel(
            name="BitmexKeys",
            fields=[
                ("api_key", models.CharField(max_length=500)),
                (
                    "secrets_key",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinanceKeys",
            fields=[
                ("api_key", models.CharField(max_length=500)),
                (
                    "secret_key",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Binanace_keys",
            },
        ),
    ]
