# Generated by Django 4.1.4 on 2023-02-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_exchanges", "0002_botstop"),
    ]

    operations = [
        migrations.AddField(
            model_name="botstop",
            name="status",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
