# Generated by Django 3.2.16 on 2023-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0002_alter_fills_clientorderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exception',
            name='status',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
