# Generated by Django 3.2.16 on 2023-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0003_exception_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitmex_model',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
