# Generated by Django 4.1.4 on 2023-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_exchanges", "0003_botstop_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botstop",
            name="status",
            field=models.CharField(default="false", max_length=20),
        ),
    ]
