# Generated by Django 4.1.4 on 2023-03-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_exchanges", "0004_alter_botstop_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="botstop",
            name="initial",
            field=models.CharField(default="1", max_length=20),
        ),
    ]
