# Generated by Django 3.2.16 on 2023-01-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0005_gate_model_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitmex_model',
            old_name='clOrdId',
            new_name='settlCurrency',
        ),
        migrations.RemoveField(
            model_name='bitmex_model',
            name='settleCurrency',
        ),
    ]
