# Generated by Django 4.0.5 on 2023-03-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0005_botstop_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botstop',
            name='shut_down',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
