# Generated by Django 3.2.16 on 2023-01-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0006_auto_20230120_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exception',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
