# Generated by Django 4.0.5 on 2023-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0007_alter_binance_model_table_alter_binancekeys1_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shut_down', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='botstop',
            name='shut_down',
        ),
    ]
