# Generated by Django 4.0.5 on 2023-03-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exchanges', '0008_killbot_remove_botstop_shut_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botstop',
            name='status',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
