# Generated by Django 4.0.5 on 2023-03-21 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_exchanges', '0009_alter_botstop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsModel',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=200)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
