# Generated by Django 4.1.4 on 2023-02-01 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 1, 6, 24, 14, 621084), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="124.253.223.208", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 1, 6, 24, 14, 621084), max_length=200
            ),
        ),
    ]
