# Generated by Django 4.1.4 on 2023-02-11 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 11, 6, 23, 49, 666434),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="124.253.220.242", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 11, 6, 23, 49, 666434),
                max_length=200,
            ),
        ),
    ]
