# Generated by Django 4.1.4 on 2023-02-02 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_created_at_alter_user_log_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 2, 11, 35, 9, 217068), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="124.253.252.129", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 2, 11, 35, 9, 217068), max_length=200
            ),
        ),
    ]
