# Generated by Django 4.1.4 on 2023-02-04 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="210.56.99.36", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 4, 8, 32, 2, 178750), max_length=200
            ),
        ),
    ]
