# Generated by Django 4.1.4 on 2023-02-17 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_created_at_alter_user_log_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="210.56.96.222", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 17, 8, 17, 21, 667233),
                max_length=200,
            ),
        ),
    ]
