# Generated by Django 4.1.4 on 2023-02-04 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_log_id_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="124.253.15.3", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 4, 10, 58, 23, 130893),
                max_length=200,
            ),
        ),
    ]
