# Generated by Django 4.1.4 on 2023-02-17 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_log_id_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 17, 11, 57, 13, 287387),
                max_length=200,
            ),
        ),
    ]
