# Generated by Django 4.1.4 on 2023-02-25 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="124.253.61.68", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 25, 12, 27, 54, 303777),
                max_length=200,
            ),
        ),
    ]
