# Generated by Django 4.1.4 on 2023-02-27 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_user_log_id_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="210.56.97.215", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 27, 6, 43, 38, 44849), max_length=200
            ),
        ),
    ]
