# Generated by Django 4.1.4 on 2023-02-27 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_user_log_id_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 2, 27, 7, 21, 34, 516193),
                max_length=200,
            ),
        ),
    ]
