# Generated by Django 4.1.4 on 2023-03-01 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="log_id",
            field=models.CharField(default="124.253.220.226", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 3, 1, 11, 9, 19, 264103), max_length=200
            ),
        ),
    ]
