# Generated by Django 3.2.18 on 2023-03-13 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='log_id',
            field=models.CharField(default='49.43.97.52', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default=datetime.datetime(2023, 3, 13, 5, 6, 13, 808464), max_length=200),
        ),
    ]
