# Generated by Django 4.1.4 on 2023-02-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmodel",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="smsmodel",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
