# Generated by Django 4.1.4 on 2023-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0002_alter_emailmodel_name_alter_smsmodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app_model",
            name="app_logo",
            field=models.CharField(default="2", max_length=200),
        ),
    ]
